### ISSUE TITLE
deps-extensions is deprecated

### ISSUE THREAD

**Issue by Bakkie123** [ayal/headly#4]
Result:

TypeError: Cannot set property 'add_reactive_variable' of undefined
at app/packages/deps-extensions/deps-extensions.js:16:35
at app/packages/deps-extensions/deps-extensions.js:117:2
at /Users/.../.meteor/local/build/server/server.js:298:12
at Array.forEach (native)
at Function._.each._.forEach (/Users/.../.meteorite/meteors/meteor/meteor/9bb2b5447e845c4f483df5e9b42a2c1de5ab909b/dev_bundle/lib/node_modules/underscore/underscore.js:78:11)
at run (/Users/.../.meteor/local/build/server/server.js:239:7)
=> Exited with code: 1

**Comment by ayal** [comment]
sorry, i have no idea what it was doing there in the first place.. i removed it from smart.json and it seems i was just able to re-publish it to atmosphere

**Comment by Bakkie123** [comment]
alright great!!
