### ISSUE TITLE
having issue in fibers/futures.js using meteor 0.7

### ISSUE THREAD

**Issue by faceyspacey** [ayal/headly#6]
I'm getting the following error:

```
=> Running Meteor from a checkout -- overrides project version (0.7.0.1)

[[[[[ ~/Meteor/emilio-television ]]]]]

=> Meteor server running on: http://localhost:3000/
W20131226-02:49:00.948(-8)? (STDERR) /Users/jamesgillmore/.meteorite/meteors/meteor/meteor/cbde5bd4875524f3ade7f3baef417a43ec1b9474/dev_bundle/lib/node_modules/fibers/future.js:173
W20131226-02:49:01.048(-8)? (STDERR)                        throw(ex);
W20131226-02:49:01.048(-8)? (STDERR)                              ^
W20131226-02:49:01.058(-8)? (STDERR) TypeError: Cannot call method 'use' of undefined
W20131226-02:49:01.059(-8)? (STDERR)     at Package (packages/headly/headly_server.js:18)
W20131226-02:49:01.059(-8)? (STDERR)     at Package (packages/headly/headly_server.js:42)
W20131226-02:49:01.059(-8)? (STDERR)     at packages/headly.js:61:4
W20131226-02:49:01.060(-8)? (STDERR)     at packages/headly.js:68:3
W20131226-02:49:01.060(-8)? (STDERR)     at /Users/jamesgillmore/Meteor/emilio-television/.meteor/local/build/programs/server/boot.js:155:10
W20131226-02:49:01.060(-8)? (STDERR)     at Array.forEach (native)
W20131226-02:49:01.061(-8)? (STDERR)     at Function._.each._.forEach (/Users/jamesgillmore/.meteorite/meteors/meteor/meteor/cbde5bd4875524f3ade7f3baef417a43ec1b9474/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20131226-02:49:01.061(-8)? (STDERR)     at /Users/jamesgillmore/Meteor/emilio-television/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Meteor server restarted
```

**Comment by faceyspacey** [comment]
could this be the solution:

http://stackoverflow.com/questions/18244108/meteor-0-6-5-update-underscore-error
